### ISSUE TITLE
Installation issue on Gentoo Prefix

### ISSUE THREAD

**Issue by bedroge** [TACC/Lmod#517]
With version 8.4.25 and newer I'm encountering the following issue when trying to install Lmod in a Gentoo Prefix environment:

```
./configure '--with-siteControlPrefix' '--with-siteName=Gentoo' '--with-syshost=Gentoo' '--with-lua_include=/usr/include/lua5.1' '--with-lua=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/lua5.1' '--with-luac=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/luac5.1' '--with-module-root-path=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/modulefiles' '--with-spiderCacheDir=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/lmod_cache/spider_cache' '--with-updateSystemFn=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/lmod_cache/system.txt' '--prefix=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/share/Lmod' '--with-caseIndependentSorting' '--without-hiddenItalic' '--with-exportedModuleCmd' '--with-useDotFiles' '--without-redirect' '--with-extendedDefault' '--with-cachedLoads' '--without-duplicatePaths' '--with-autoSwap'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
DUPLICATE_PATHS=no
LMOD_ALLOW_ROOT_USE=yes
SITE_MSG_FILE=<empty>
LMOD_OVERRIDE_LANG=<empty>
CASE_INDEPENDENT_SORTING=yes
COLORIZE=yes
HIDDEN_ITALIC=no
EXACT_MATCH=no
AUTO_SWAP=yes
EXPORT_MODULE=yes
REDIRECT=no
MODULEPATH_ROOT=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/modulefiles
ANCIENT=86400
SHORT_TIME=2
USE_DOT_FILES=yes
SPIDER_CACHE_DIRS=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/lmod_cache/spider_cache
SPIDER_CACHE_DESCRIPT_FN=
UPDATE_SYSTEM_FN=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/etc/lmod_cache/system.txt
PREPEND_BLOCK=normal
SITE_NAME=Gentoo
SYSHOST=Gentoo
ALLOW_TCL_MFILES=yes
DISABLE_NAME_AUTOSWAP=no
MPATH_AVAIL=no
SETTARG=no
IGNORE_DIRS=.svn,.git,.hg,.bzr
PIN_VERSIONS=no
TMOD_PATH_RULE=no
TMOD_FIND_FIRST=no
LUA_INCLUDE=/usr/include/lua5.1
CACHED_LOADS=yes
EXTENDED_DEFAULT=yes
SUPPORT_KSH=no
MODULEPATH_INIT=@PKG@/init/.modulespath
SITE_CONTROLLED_PREFIX=yes
USE_BUILT_IN_PKGS=no
SILENCE_SHELL_DEBUGGING=no
FAST_TCL_INTERP=yes
AVAIL_EXTENSIONS=yes
PATH_TO_LUA=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/lua5.1
PATH_TO_LUAC=/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/luac5.1
LUA_SUFFIX=no
checking for pkg-config... /cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/bin/pkg-config
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/home/ec2-user/Lmod-8.4.25':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
```

This seems to be caused by how `TCL_INCLUDE` is being set and used to define `CPPFLAGS`. As Gentoo Prefix has a non-default sysroot (here: `/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64`), the `configure` script will not find the Tcl headers in `/usr/include`. So, looking at the `configure` script, it will then run `pkg-config --cflags tcl` to find the headers, but that doesn't return anything either, as they are in a Gentoo Prefix system path (`/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/include`). This means `CPPFLAGS` ultimately gets set to just `-I `, which causes issues. 

I could confirm it by setting `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1`, to enforce that `pkg-config` does also return system paths. Also explicitly setting `TCL_INCLUDE='/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/x86_64/usr/include' solves the issue, and so does disabling the line that sets `CPPFLAGS` in the `configure` script.

But I think it would be better if the script would detect that `pkg-config` returns an empty string. In that case, it could probably just set `CPPFLAGS` to an empty string?

**Comment by amadio** [comment]
I would suggest to use `pkg-config --cflags-only-I tcl` and not post-processing the result.

**Comment by rtmclay** [comment]
Thanks for the bug report and the suggestion!  I have updated Lmod and released version 8.5.4.  Please see if new version works better for you.

**Comment by amadio** [comment]
I get this with the new version:
```
x86_64-pc-linux-gnu-gcc -O2 -pipe -O2 -pipe -DLUA_COMPAT_MODULE -fPIC -I-I/cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64/usr/include/lua5.1    -c -o tcl2lua.o tcl2lua.c
make FILELIST="init/profile.in init/profile.fish.in init/cshrc.in" DIRLOC=/tmp/portage/sys-cluster/lmod-8.5.4/image/cvmfs/sft.cern.ch/lcg/contrib/gentoo/linux/x86_64/usr/share/Lmod/init    __installMe
make[1]: Entering directory '/tmp/portage/sys-cluster/lmod-8.5.4/work/Lmod-8.5.4'
make[1]: Entering directory '/tmp/portage/sys-cluster/lmod-8.5.4/work/Lmod-8.5.4'
tcl2lua.c:1:10: fatal error: lua.h: No such file or directory
    1 | #include <lua.h>
      |          ^~~~~~~
```
Note the double `-I-I` in the include directory for Lua.

**Comment by amadio** [comment]
Maybe it's simpler to check if pkg-config has returned an empty string for `$TCL_INCLUDE` before adding `CPPFLAGS="-I $TCL_INCLUDE"`, or to set `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1` when calling pkg-config, as we've done to fix the package for 8.5.3.

**Comment by rtmclay** [comment]
I believe that I got the code for TCL_INCLUDE correct before but I messed up setting LUA_INCLUDE.  I have fixed it for me in this new version. Please test Lua 8.5.6 to see if it works for you.

**Comment by amadio** [comment]
With the changes you made, you don't need to set `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1` anymore. I meant that as an alternative to the changes you had made. The part that handles `TCL_INCLUDE` worked with 8.5.4.

**Comment by amadio** [comment]
FWIW, version 8.5.6 works without the need for the workaround we added in 8.5.3. I think this can be closed. Thanks!

**Comment by bedroge** [comment]
Yep, this version also works for me. Thanks @rtmclay!

**Comment by amadio** [comment]
Added to Gentoo as well: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=47e2738b19b39b65617bdcb4e619a3ba3c799037.
